__PANDAS__

- Dataframe -special object to data in tabular form(rows & column)-

In [4]:
import pandas as pd
import numpy as np

In [6]:
#Try to create a DataFrame

user_data = {
    
    "MarksA" : np.random.randint(1,100,5),
    "MarksB" : np.random.randint(50,100,5),
    "MarksC" : np.random.randint(1,100,5)
    
}

In [9]:
user_data

{'MarksA': array([53, 27, 83, 36,  2]),
 'MarksB': array([71, 58, 66, 57, 69]),
 'MarksC': array([21, 70, 71, 45, 22])}

In [27]:
df = pd.DataFrame(user_data,dtype = float)
print(df)

   MarksA  MarksB  MarksC
0    53.0    71.0    21.0
1    27.0    58.0    70.0
2    83.0    66.0    71.0
3    36.0    57.0    45.0
4     2.0    69.0    22.0


In [28]:
df.head()

MarksA  MarksB  MarksC
0    53.0    71.0    21.0
1    27.0    58.0    70.0
2    83.0    66.0    71.0
3    36.0    57.0    45.0
4     2.0    69.0    22.0

In [30]:
df.to_csv("marks.csv")

In [31]:
my_data = pd.read_csv("marks.csv")
my_data = my_data.drop(columns=['Unnamed: 0'])
my_data

MarksA  MarksB  MarksC
0    53.0    71.0    21.0
1    27.0    58.0    70.0
2    83.0    66.0    71.0
3    36.0    57.0    45.0
4     2.0    69.0    22.0

In [32]:
df.describe()

MarksA     MarksB     MarksC
count   5.00000   5.000000   5.000000
mean   40.20000  64.200000  45.800000
std    30.19437   6.379655  24.509182
min     2.00000  57.000000  21.000000
25%    27.00000  58.000000  22.000000
50%    36.00000  66.000000  45.000000
75%    53.00000  69.000000  70.000000
max    83.00000  71.000000  71.000000

__PANDA BASICS PART 2__

In [33]:
my_data.tail(n=3)

MarksA  MarksB  MarksC
2    83.0    66.0    71.0
3    36.0    57.0    45.0
4     2.0    69.0    22.0

In [34]:
#ROW


df.iloc[3]

MarksA    36.0
MarksB    57.0
MarksC    45.0
Name: 3, dtype: float64

In [35]:
#ROW & COLUMN

df.iloc[3][1]

57.0

In [39]:
idx = df.columns.get_loc("MarksB")
df.iloc[3,idx]

57.0

In [40]:
#SORT YOUR DATAFRAME

my_data

MarksA  MarksB  MarksC
0    53.0    71.0    21.0
1    27.0    58.0    70.0
2    83.0    66.0    71.0
3    36.0    57.0    45.0
4     2.0    69.0    22.0

In [42]:
my_data.sort_values(by="MarksC",ascending = "True")

MarksA  MarksB  MarksC
0    53.0    71.0    21.0
4     2.0    69.0    22.0
3    36.0    57.0    45.0
1    27.0    58.0    70.0
2    83.0    66.0    71.0

In [44]:
#DATAFRAME INTO NUMPY ARARY

data_array = my_data.values

In [49]:
print(type(my_data))
print(my_data.shape)

<class 'pandas.core.frame.DataFrame'>
(5, 3)


In [52]:
print(type(data_array))
print(data_array)

<class 'numpy.ndarray'>
[[53. 71. 21.]
 [27. 58. 70.]
 [83. 66. 71.]
 [36. 57. 45.]
 [ 2. 69. 22.]]


In [51]:
data_array[2][2]

71.0

In [57]:
#NUMPY BACK INTO DATAFRAME
new_df = pd.DataFrame(data_array,dtype='int',columns=["Physics","Chem","Maths"])
print(type(new_df))

<class 'pandas.core.frame.DataFrame'>


In [58]:
print(new_df)

   Physics  Chem  Maths
0       53    71     21
1       27    58     70
2       83    66     71
3       36    57     45
4        2    69     22


In [64]:
new_df.to_csv("PCM.csv",index = False)

In [67]:
pcm = pd.read_csv("PCM.csv")

In [68]:
print(pcm)

   Physics  Chem  Maths
0       53    71     21
1       27    58     70
2       83    66     71
3       36    57     45
4        2    69     22
